name: TeXLive

on:
  workflow_dispatch:
  schedule:
    # 每周一的0:37分执行 (北京时间+8)
    - cron: "37 0 * * 1"
  push:
    branches: [main]
    paths:
      - 'texlive-en/Dockerfile.en'
      - 'texlive-en/texlive.profile'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: hankyproject
          password: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          docker build --file ./texlive-en/Dockerfile.en --tag ghcr.io/hankyproject/texlive:latest ./texlive-en
          docker push ghcr.io/hankyproject/texlive:latest

      # - name: Set up QEMU
      #   uses: docker/setup-qemu-action@v3
      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v3
      # - name: Push to GitHub Container Registry
      #   uses: docker/build-push-action@v6
      #   with:
      #     context: ./texlive-en
      #     file: ./texlive-en/Dockerfile.en
      #     platforms: amd64
      #     push: true
      #     tags: "ghcr.io/hankyproject/texlive:latest"
